/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThermostatRequest } from '../../models/thermostat-request';
import { ThermostatResponse } from '../../models/thermostat-response';

export interface AddThermostat$Params {
      body: ThermostatRequest
}

export function addThermostat(http: HttpClient, rootUrl: string, params: AddThermostat$Params, context?: HttpContext): Observable<StrictHttpResponse<ThermostatResponse>> {
  const rb = new RequestBuilder(rootUrl, addThermostat.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThermostatResponse>;
    })
  );
}

addThermostat.PATH = '/thermostat';
