/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoorLockRequest } from '../../models/door-lock-request';
import { DoorLockResponse } from '../../models/door-lock-response';

export interface AddDoorLock$Params {
      body: DoorLockRequest
}

export function addDoorLock(http: HttpClient, rootUrl: string, params: AddDoorLock$Params, context?: HttpContext): Observable<StrictHttpResponse<DoorLockResponse>> {
  const rb = new RequestBuilder(rootUrl, addDoorLock.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DoorLockResponse>;
    })
  );
}

addDoorLock.PATH = '/doorLock';
