/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { WeatherSensorControllerService } from './services/weather-sensor-controller.service';
import { LightSwitchControllerService } from './services/light-switch-controller.service';
import { DoorLockControllerService } from './services/door-lock-controller.service';
import { DeviceControllerService } from './services/device-controller.service';
import { AirQualitySensorControllerService } from './services/air-quality-sensor-controller.service';
import { ThermostatControllerService } from './services/thermostat-controller.service';
import { SmokeSensorControllerService } from './services/smoke-sensor-controller.service';
import { SmartOutletControllerService } from './services/smart-outlet-controller.service';
import { AuthenticationControllerService } from './services/authentication-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    WeatherSensorControllerService,
    LightSwitchControllerService,
    DoorLockControllerService,
    DeviceControllerService,
    AirQualitySensorControllerService,
    ThermostatControllerService,
    SmokeSensorControllerService,
    SmartOutletControllerService,
    AuthenticationControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
