/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AirQualitySensorRequest {
  accuracy?: number;
  co2AlertThreshold?: number;
  deviceDescription?: string;
  deviceModel?: string;
  deviceName?: string;
  location?: string;
  manufacturer?: string;
  pm25AlertThreshold?: number;
  serialNumber?: string;
  updateFrequency?: number;
}
