/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AirQualitySensorDataResponse {
  airQualityIndex?: number;
  co2AlertThreshold?: number;
  co2Level?: number;
  coLevel?: number;
  humidity?: number;
  no2Level?: number;
  o3Level?: number;
  pm10Level?: number;
  pm25AlertThreshold?: number;
  pm25Level?: number;
  pressure?: number;
  sensorId?: number;
  temperature?: number;
  updateFrequency?: number;
  vocLevel?: number;
}
