/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AirQualitySensorResponse {
  accuracy?: number;
  airQualityIndex?: number;
  co2AlertThreshold?: number;
  co2Level?: number;
  coLevel?: number;
  deviceName?: string;
  hasWifiModule?: boolean;
  humidity?: number;
  id?: number;
  isActive?: boolean;
  lastCalibrationDate?: string;
  no2Level?: number;
  o3Level?: number;
  pm10Level?: number;
  pm25AlertThreshold?: number;
  pm25Level?: number;
  pressure?: number;
  temperature?: number;
  turnOn?: boolean;
  updateFrequency?: number;
  vocLevel?: number;
}
