/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlarmSensitivityRequest {
  sensitivity?: 'LOW' | 'MEDIUM' | 'HIGH';
  valueForSensitivity?: number;
}
