/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirQualitySensorRequest } from '../../models/air-quality-sensor-request';
import { AirQualitySensorResponse } from '../../models/air-quality-sensor-response';

export interface AddNewAirQualitySensor$Params {
      body: AirQualitySensorRequest
}

export function addNewAirQualitySensor(http: HttpClient, rootUrl: string, params: AddNewAirQualitySensor$Params, context?: HttpContext): Observable<StrictHttpResponse<AirQualitySensorResponse>> {
  const rb = new RequestBuilder(rootUrl, addNewAirQualitySensor.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirQualitySensorResponse>;
    })
  );
}

addNewAirQualitySensor.PATH = '/air-quality-sensor';
