/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LightSwitchRequest } from '../../models/light-switch-request';
import { LightSwitchResponse } from '../../models/light-switch-response';

export interface AddLightSwitch$Params {
      body: LightSwitchRequest
}

export function addLightSwitch(http: HttpClient, rootUrl: string, params: AddLightSwitch$Params, context?: HttpContext): Observable<StrictHttpResponse<LightSwitchResponse>> {
  const rb = new RequestBuilder(rootUrl, addLightSwitch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LightSwitchResponse>;
    })
  );
}

addLightSwitch.PATH = '/lightSwitch';
